### ISSUE TITLE
I don't understand how to use this...

### ISSUE THREAD

**Issue by junobonnie** [jchelly/gadgetviewer#13]
How do i install gadgetveiwer?

'make' and 'make install' was not work at gadgetviewer-1.1.1$ directory.

I don't speak English, so I have limitations in finding information. 

Somebody help me...

**Comment by jchelly** [comment]
If you downloaded a release file (e.g. from https://github.com/jchelly/gadgetviewer/releases) then you just need to run the configure script first:
```
cd gadgetviewer-1.1.1
./configure --prefix=<install location>
make
make install
```
where <install location> is the path to install it in. You'll need to have C and Fortran compilers and the GTK2 library installed on your system.

If you cloned the repository you need to run an extra command to create the configure script first:
```
cd gadgetviewer-1.1.1
./autogen.sh
```
There's more information in the README file: https://github.com/jchelly/gadgetviewer/blob/master/README.md

**Comment by junobonnie** [comment]
Thank you!!!!! It works really well!
